[package]
name = "rmw_so"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
blake3 = "1.1.0"
dirs = "4.0.0"
ed25519-dalek-blake3 = "1.0.5"
flutter_rust_bridge = "1.2.1"
